// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvdxququfjptexbvolfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2ZHhxdXF1ZmpwdGV4YnZvbGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Mjg1MjksImV4cCI6MjA1OTQwNDUyOX0.RgLCJ4dsIpFlZ3gtNJTVwCHUtbYQaqjt-z_De8LAR0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);